### ISSUE TITLE
Please build with Torch 2.0

### ISSUE THREAD

**Issue by SlimeVRX** [takizuki/pytorch3d#1]
Current Colab: Python 3.9.16, Torch 2.0, Cuda 11.8
Please build with Torch 2.0
Thank you very much!

**Comment by takizuki** [comment]
Thank you for your comment.
i built 0.7.3 and confirmed the latest wheel works with PyTorch 2.0.0+cu118
```
!pip install https://takizuki.github.io/pytorch3d/pytorch3d-0.7.3-cp39-cp39-linux_x86_64.whl
```
check it out!

**Comment by SlimeVRX** [comment]
Thank you very much!
