### ISSUE TITLE
Where are stored wheels .whl cached files?

### ISSUE THREAD

**Issue by SlimeVRX** [takizuki/pytorch3d#2]
Hi

In Colab, I just installed pytorch 3D. Where are stored wheels .whl cached files?

Thank you very much!

![image](https://user-images.githubusercontent.com/99313947/235285216-1fde5d46-571e-4c9a-823f-9a2299132699.png)

**Comment by takizuki** [comment]
i'm not an instructor of pytorch3d.
build time for pytorch3d is 55 minutes.
you can read the code by yourself.
it's not difficult.
How about searching for all filenames?

**Comment by SlimeVRX** [comment]
Hi! Thank

I did it according to this [guide](https://youtu.be/AM2dgUAdwaQ)

Thank you very much!

**Comment by takizuki** [comment]
```
pip wheel "git+https://github.com/facebookresearch/pytorch3d.git@stable"
```
is simpler.

**Comment by SlimeVRX** [comment]
Many thank!
